### ISSUE TITLE
Creating InfluxDB(s) gives error

### ISSUE THREAD

**Issue by rohit-gohri** [mrlesmithjr/ansible-influxdb#12]
The step gives error:
`TypeError: int() argument must be a string or a number, not 'NoneType'`

It is related to https://github.com/ansible-collections/community.general/issues/190

A simple fix is to add `udp_port: influx_udb['bind_port']` to both this and `Creating InfluxDB Retention Policies` steps

**Comment by mrlesmithjr** [comment]
@rohit-gohri Thanks for reporting this.

**Comment by rohit-gohri** [comment]
Thanks for the quick fix! :+1:

**Comment by mrlesmithjr** [comment]
Absolutely! Again, thanks for reporting this issue.
