### ISSUE TITLE
AnsibleUndefinedVariable

### ISSUE THREAD

**Issue by htbase** [mrlesmithjr/ansible-influxdb#6]
Hi there

I receive the following when installing the role:

TASK [ansible-influxdb : config | Configuring InfluxDB] **************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'https_enabled'"}

Any ideas?

Thanks

**Comment by mrlesmithjr** [comment]
@htbase Seems odd because this is definitely defined in [defaults/main.yml](../defaults/main.yml) unless maybe `group_vars` or `host_vars` have been defined and possibly undefined. Did you by chance sort this out?

**Comment by mrlesmithjr** [comment]
@htbase Just wanted to check with you and see if this was still an issue for you. I have not been able to duplicate this issue as of yet.
